package Presentacion;

import Entidad.Aula;
import Datos.AulaDAO;
import java.awt.image.BufferedImage;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import org.jfree.chart.*;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

public class DialogAula extends javax.swing.JDialog {
    AulaDAO p = new AulaDAO();
    boolean reg;
    JFreeChart grafico;
    DefaultCategoryDataset Datos = new DefaultCategoryDataset();
    DefaultTableModel modelo = new DefaultTableModel();
    String nombreColumnas[] = {"IDAULA","NUMERO DE AULA","CAPACIDAD"};
    Aula aulaSelec = new Aula();
    
    public DialogAula(){
        super(FrmPrincipal.getInst(),true);
        initComponents();
         try {
             p.mostrarAula(modelo);
         } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
         }
         grafico();
        //Buscar
        txtbuscaraula.requestFocus();
        limpiarTextos();
        textos(false);
        controles(true);
        setLocationRelativeTo(null);
    }

    public void grafico(){
        int a=0;
        String b;
        for(int i=0;i<modelo.getRowCount();i++){
            a=Integer.parseInt(modelo.getValueAt(i, 2).toString());
            b=(String)modelo.getValueAt(i, 1);
            Datos.addValue(a, "Central", b);
        }
        grafico=ChartFactory.createBarChart3D("GRÁFICA DE AULAS","Número de Aula","Capacidad", 
                Datos, PlotOrientation.HORIZONTAL,true,true,false);
        ChartPanel Panel = new ChartPanel(grafico);
        BufferedImage graficoBarra=grafico.createBufferedImage
        (labelGrafico.getWidth(), labelGrafico.getHeight());
        labelGrafico.setSize(labelGrafico.getSize());
        labelGrafico.setIcon(new ImageIcon(graficoBarra));
        labelGrafico.updateUI();
    }
    
    public void limpiarTextos(){
        txtidAula.setText("");
        txtNumeroAula.setText("");
        txtbuscaraula.setText("");
        txtCapacidad.setText("");

    }
    public void textos(boolean tf){
        txtidAula.setEditable(tf);
        txtNumeroAula.setEditable(tf);
        txtbuscaraula.setEditable(!tf);
        txtCapacidad.setEditable(tf);
    }
    public void controles(boolean tf){
        btnNuevo.setEnabled(tf);
        btnRegistrar.setEnabled(!tf);
        btnCancelar.setEnabled(!tf);
        btnModificar.setEnabled(tf);
        btnEliminar.setEnabled(tf);
        btnSeleccionar.setEnabled(tf);
        btnBuscarAula.setEnabled(tf);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtidAula = new javax.swing.JTextField();
        txtNumeroAula = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        txtCapacidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        labelGrafico = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtbuscaraula = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnSeleccionar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnBuscarAula = new javax.swing.JButton();

        jLabel9.setText("jLabel9");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setText("jLabel6");

        jLabel10.setText("jLabel10");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aula");
        setMinimumSize(new java.awt.Dimension(525, 590));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("REGISTRO DE AULAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/insigniac.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 56));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 56));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("IdAula:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 40, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Número Aula:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 20));

        txtidAula.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153))));
        getContentPane().add(txtidAula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 90, 27));

        txtNumeroAula.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153))));
        txtNumeroAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroAulaActionPerformed(evt);
            }
        });
        txtNumeroAula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroAulaKeyTyped(evt);
            }
        });
        getContentPane().add(txtNumeroAula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 107, 90, 27));

        btnNuevo.setBackground(new java.awt.Color(216, 216, 216));
        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anadir.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102))));
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 100, -1));

        btnCancelar.setBackground(new java.awt.Color(216, 216, 216));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton-x.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102))));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 100, 28));

        btnModificar.setBackground(new java.awt.Color(216, 216, 216));
        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/actualizado.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102))));
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 100, 28));

        btnRegistrar.setBackground(new java.awt.Color(216, 216, 216));
        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/registrarse.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102))));
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 110, -1));

        txtCapacidad.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153))));
        txtCapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapacidadActionPerformed(evt);
            }
        });
        txtCapacidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCapacidadKeyTyped(evt);
            }
        });
        getContentPane().add(txtCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 90, 27));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Capacidad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 20));

        btnEliminar.setBackground(new java.awt.Color(216, 216, 216));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102))));
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 110, 28));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(labelGrafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 470));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 14, 420, 470));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102)), "BUSCAR POR NÚMERO DE AULA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtbuscaraula.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153))));
        txtbuscaraula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscaraulaActionPerformed(evt);
            }
        });
        txtbuscaraula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscaraulaKeyReleased(evt);
            }
        });
        jPanel2.add(txtbuscaraula, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 16, 70, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Código de aula:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 18, -1, -1));

        tabla.setModel(modelo);
        jScrollPane3.setViewportView(tabla);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 470, 250));

        btnSeleccionar.setBackground(new java.awt.Color(216, 216, 216));
        btnSeleccionar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/seleccione.png"))); // NOI18N
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102))));
        btnSeleccionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        jPanel2.add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 130, -1));

        btnSalir.setBackground(new java.awt.Color(216, 216, 216));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salidab.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102))));
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 100, -1));

        btnBuscarAula.setBackground(new java.awt.Color(216, 216, 216));
        btnBuscarAula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscarAula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar.png"))); // NOI18N
        btnBuscarAula.setText("Buscar");
        btnBuscarAula.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102))));
        btnBuscarAula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAulaActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscarAula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 110, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 136, 490, 350));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, 952, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroAulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroAulaActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        reg=true;
        limpiarTextos();
        textos(true);
        controles(false);
        txtidAula.requestFocus();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        String idAula;
        idAula = JOptionPane.showInputDialog("INGRESAR ID DEL AULA A ELIMINAR: ");
        Aula aula;
        try{
            aula = AulaDAO.getInstancia().buscaAula(idAula);
            if(aula != null){
                txtidAula.setText(aula.getIdAula());
                txtNumeroAula.setText(""+aula.getNumeroAula());
                txtCapacidad.setText(""+aula.getCapacidad());
                int resp = JOptionPane.showConfirmDialog(this,"¿DESEAS ELIMINARLO","ELIMIAR DATO",JOptionPane.YES_NO_OPTION );
                if(resp == JOptionPane.YES_OPTION){
                    AulaDAO.getInstancia().eliminar(idAula);
                    JOptionPane.showMessageDialog(this,"REGISTRO ELIMINADO");
                }
                limpiarTextos();
                
            }else{
                JOptionPane.showMessageDialog(this,"EL ID DEL AULA NO EXISTE");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }  
        txtbuscaraula.requestFocus();
        try {
             p.mostrarAula(modelo);
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        grafico();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:    
        limpiarTextos();
        textos(false);
        controles(true);
        txtbuscaraula.requestFocus();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        String idAula;
        idAula = JOptionPane.showInputDialog("INGRESAR ID DEL AULA A MODIFICAR: ");
        Aula aula;
        try{
            aula = AulaDAO.getInstancia().buscaAula(idAula);
            if(aula != null){
                txtidAula.setText(aula.getIdAula());
                txtNumeroAula.setText(""+aula.getNumeroAula());
                txtCapacidad.setText(""+aula.getCapacidad());
                reg=false;
                textos(true);
                txtidAula.setEnabled(false);
                controles(false);
            }else{
                JOptionPane.showMessageDialog(this,"EL ID DEL AULA NO EXISTE");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }  
         try {
             p.mostrarAula(modelo);
         } catch (SQLException ex) {
             JOptionPane.showMessageDialog(this, ex.getMessage());
         }
         grafico();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
       if(txtidAula.getText().equals("")){
           JOptionPane.showMessageDialog(this, "INGRESAR UN ID");
           txtidAula.requestFocus();
           return;
       }
       if(txtNumeroAula.getText().equals("")){
           JOptionPane.showMessageDialog(this, "INGRESAR EL NUMERO DE AULA");
           txtNumeroAula.requestFocus();
           return;
       }
       if(txtCapacidad.getText().equals("")){
           JOptionPane.showMessageDialog(this, "INGRESAR LA CAPACIDAD DEL AULA ");
           txtCapacidad.requestFocus();
       }
       
       String idAula;
       int numeroAula,capacidad;
       idAula = txtidAula.getText();
       numeroAula = Integer.parseInt(txtNumeroAula.getText());
       capacidad = Integer.parseInt(txtCapacidad.getText());
       Aula x = new Aula(idAula,numeroAula,capacidad);
       if(reg){
            try{
               p.insertar(x);
                JOptionPane.showMessageDialog(this, "AULA REGISTRADA");
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            } 
       }else{
           try{
                p.actualizar(x);
                JOptionPane.showMessageDialog(this, "AULA MODIFICADA");
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            } 
       }
       txtbuscaraula.requestFocus();
       try {
             p.mostrarAula(modelo);
         } catch (SQLException ex) {
             JOptionPane.showMessageDialog(this, ex.getMessage());
         }
       limpiarTextos();
       textos(false);
       controles(true);
       grafico();
       
       
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtbuscaraulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscaraulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscaraulaActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        int i = tabla.getSelectedRow();
        if(i!=-1) {
            aulaSelec.setIdAula(modelo.getValueAt(i, 0).toString());
            aulaSelec.setNumeroAula(Integer.parseInt(modelo.getValueAt(i, 1).toString()));
            aulaSelec.setCapacidad(Integer.parseInt(modelo.getValueAt(i, 2).toString()));
            this.dispose();
        } else
        JOptionPane.showMessageDialog(null, "DEBES SELECCIONAR UN ELEMENTO");
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnBuscarAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAulaActionPerformed
       String n=txtbuscaraula.getText();
         try {
            p.buscarPorCodigo(n, modelo);
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null,"ERROR: "+ ex.getMessage() );
        }
     
        
    }//GEN-LAST:event_btnBuscarAulaActionPerformed

    private void txtCapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidadActionPerformed

    private void txtbuscaraulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscaraulaKeyReleased
         String n=txtbuscaraula.getText();
         try {
            p.buscarPorCodigo(n, modelo);
         } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null,"ERROR: "+ ex.getMessage() );
         }
    }//GEN-LAST:event_txtbuscaraulaKeyReleased

    private void txtNumeroAulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroAulaKeyTyped
        char validar= evt.getKeyChar();
        if (txtNumeroAula.getText().length()>4)
            evt.consume();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"INGRESAR SOLO NUMEROS");
        }
    }//GEN-LAST:event_txtNumeroAulaKeyTyped

    private void txtCapacidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCapacidadKeyTyped
        char validar= evt.getKeyChar();
        if (txtCapacidad.getText().length()>4)
            evt.consume();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"INGRESAR SOLO NUMEROS");
        }
    }//GEN-LAST:event_txtCapacidadKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAula;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelGrafico;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtNumeroAula;
    private javax.swing.JTextField txtbuscaraula;
    private javax.swing.JTextField txtidAula;
    // End of variables declaration//GEN-END:variables
}
